/*! AgroPrix api.js - generated from api.js.src on 2026-04-18 - DO NOT EDIT; edit the .src file and run `python build_js.py` */
(function(AP){var API_TIMEOUT_MS=8000;var CACHE_PREFIX='ap_cache_';var CACHE_TTL_MS=6*60*60*1000;function cacheSet(key,data){try{localStorage.setItem(CACHE_PREFIX+key,JSON.stringify({ts:Date.now(),data:data}));}catch(e){}}
function cacheGet(key){try{var raw=localStorage.getItem(CACHE_PREFIX+key);if(!raw)return null;var entry=JSON.parse(raw);if(Date.now()-entry.ts>CACHE_TTL_MS)return null;return entry.data;}catch(e){return null;}}
async function fetchRobust(url,cacheKey){for(var attempt=0;attempt<2;attempt++){try{var resp=await fetch(url,{signal:AbortSignal.timeout(API_TIMEOUT_MS)});if(!resp.ok)throw new Error('HTTP '+resp.status);var json=await resp.json();if(cacheKey)cacheSet(cacheKey,json);return json;}catch(e){if(attempt===0){await new Promise(function(r){setTimeout(r,1200);});}}}
if(cacheKey){var cached=cacheGet(cacheKey);if(cached){console.warn('[AgroPrix] Réseau indisponible — données cache utilisées pour',cacheKey);cached._fromCache=true;return cached;}}
return null;}
function checkAPI(){fetch(AP.API_BASE+'/',{method:'GET',signal:AbortSignal.timeout(3000)}).then(function(r){if(r.ok){AP.API_AVAILABLE=true;}}).catch(function(){AP.API_AVAILABLE=false;});}
function periodToStartDate(periodKey){var now=new Date();var y=now.getFullYear(),m=now.getMonth()+1;switch(periodKey){case'12m':return(y-1)+'-'+String(m).padStart(2,'0')+'-01';case'3y':return(y-3)+'-'+String(m).padStart(2,'0')+'-01';case'5y':return(y-5)+'-'+String(m).padStart(2,'0')+'-01';case'10y':return(y-10)+'-'+String(m).padStart(2,'0')+'-01';default:return(y-1)+'-01-01';}}
async function fetchPrices(country,commodity,periodKey){var wfpName=AP.cultureToWFP[commodity]||commodity;var startDate=periodToStartDate(periodKey);var url=AP.API_BASE+'/api/prices/monthly?country='+country
+'&commodity='+encodeURIComponent(wfpName)
+'&start_date='+startDate;var cacheKey='prices_'+country+'_'+wfpName+'_'+periodKey;var json=await fetchRobust(url,cacheKey);return(json&&json.data)?json.data:[];}
async function fetchMarkets(country){var url=AP.API_BASE+'/api/prices/markets?country='+country;var json=await fetchRobust(url,'markets_'+country);return(json&&json.data)?json.data:[];}
async function fetchCompare(commodity){var wfpName=AP.cultureToWFP[commodity]||commodity;var url=AP.API_BASE+'/api/prices/compare?commodity='+encodeURIComponent(wfpName);var json=await fetchRobust(url,'compare_'+wfpName);return(json&&json.data)?json.data:[];}
async function fetchForecast(country){var url=AP.API_BASE+'/api/weather/forecast?country='+country;var json=await fetchRobust(url,'forecast_'+country);return json||{};}
async function fetchRecommendations(country,commodity){var wfpName=AP.cultureToWFP[commodity]||commodity;var url=AP.API_BASE+'/api/recommendations/?country='+country
+'&commodity='+encodeURIComponent(wfpName);var json=await fetchRobust(url,'reco_'+country+'_'+wfpName);return json||{};}
AP.api={checkAPI:checkAPI,periodToStartDate:periodToStartDate,fetchPrices:fetchPrices,fetchMarkets:fetchMarkets,fetchCompare:fetchCompare,fetchForecast:fetchForecast,fetchRecommendations:fetchRecommendations};})(window.AgroPrix);