/*! AgroPrix app.js - generated from app.js.src on 2026-04-19 - DO NOT EDIT; edit the .src file and run `python build_js.py` */
(function(AP){'use strict';function init(){if(AP.api&&AP.api.checkAPI){AP.api.checkAPI();}
if(AP.ui&&AP.ui.updateMarkets){AP.ui.updateMarkets();}
registerServiceWorker();setupInstallPrompt();if(AP.auth&&AP.auth.initAuth){AP.auth.initAuth();}
if(AP.cgu&&AP.cgu.checkOnStartup){AP.cgu.checkOnStartup();}
handleStartupView();}
function handleStartupView(){var params=new URLSearchParams(window.location.search);var view=params.get('view');if(view&&window.showView){setTimeout(function(){var user=AP.auth?AP.auth.getUser():null;if(user&&window.showView){window.showView(view);}},800);}}
function registerServiceWorker(){if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').then(function(reg){}).catch(function(err){});}}
var deferredPrompt=null;function setupInstallPrompt(){window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredPrompt=e;var installBtn=document.getElementById('installBtn');if(installBtn){installBtn.style.display='flex';installBtn.addEventListener('click',function(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.then(function(result){deferredPrompt=null;installBtn.style.display='none';});}});}});}
function demoMode(){var demoUser={nom:'Utilisateur Demo',name:'Utilisateur Demo',email:'demo@agroprix.app',pays:'benin',country:'benin',role:'demo',plan:'demo',demo:true};localStorage.setItem('agroprix_user',JSON.stringify(demoUser));localStorage.setItem('agroprix_token','demo-token-v6');var authScreen=document.getElementById('authScreen');var appContainer=document.getElementById('appContainer');if(authScreen)authScreen.style.display='none';if(appContainer)appContainer.style.display='';var nameEl=document.querySelector('.user-name');var roleEl=document.querySelector('.user-role');var avatarEl=document.querySelector('.sidebar-footer .avatar');if(nameEl)nameEl.textContent='Utilisateur Demo';if(roleEl)roleEl.textContent='Mode Demo';if(avatarEl)avatarEl.textContent='DM';var profileName=document.getElementById('profileName');var profileEmail=document.getElementById('profileEmail');var profileCountry=document.getElementById('profileCountry');var profilePlan=document.getElementById('profilePlan');if(profileName)profileName.textContent='Utilisateur Demo';if(profileEmail)profileEmail.textContent='demo@agroprix.app';if(profileCountry)profileCountry.textContent='Benin';if(profilePlan)profilePlan.textContent='Démo — Gratuit';}
AP.app={init:init,demoMode:demoMode};window.demoMode=demoMode;if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})(window.AgroPrix);window.simulerPotentiel=function(){var surface=parseFloat(document.getElementById('propSurface').value)||0;var pays=document.getElementById('propPays').value||'benin';var region=document.getElementById('propRegion').value||'';var sol=document.getElementById('propSol').value||'';var container=document.getElementById('propResultat');if(!container)return;if(surface<=0){alert('Veuillez indiquer la superficie.');return;}
var cultures=[{nom:'Mais',emoji:'🌽',rendement:2.5,prixKg:250,saison:'Avr-Jul',score:85},{nom:'Soja',emoji:'🫘',rendement:1.8,prixKg:380,saison:'Jun-Sep',score:78},{nom:'Tomate',emoji:'🍅',rendement:15,prixKg:450,saison:'Oct-Jan',score:72},{nom:'Manioc',emoji:'🥔',rendement:12,prixKg:120,saison:'Toute annee',score:90},{nom:'Arachide',emoji:'🥜',rendement:1.2,prixKg:520,saison:'Mai-Aout',score:68}];if(sol==='alluvial'){cultures[2].score+=10;cultures[0].score+=5;}
if(sol==='sableux'){cultures[4].score+=10;cultures[3].score+=5;}
if(sol==='argileux'){cultures[0].score+=8;cultures[1].score+=5;}
cultures.sort(function(a,b){return b.score-a.score;});var html='<div style="margin-top:16px;">';html+='<h3 style="font-size:16px;font-weight:700;color:#1B4332;margin-bottom:12px;"><i data-lucide="bar-chart-3" class="lc"></i> Resultats pour '+surface+' ha</h3>';cultures.slice(0,3).forEach(function(c,i){var revenu=Math.round(surface*c.rendement*1000*c.prixKg);var revenuStr=revenu.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ');var barColor=i===0?'#2D6A4F':i===1?'#E8862A':'#6B7280';html+='<div class="card" style="padding:14px;margin-bottom:10px;border-left:4px solid '+barColor+';border-radius:0 14px 14px 0;">'
+'<div style="display:flex;justify-content:space-between;align-items:center;">'
+'<div><span style="font-size:24px;margin-right:8px;">'+c.emoji+'</span><strong style="font-size:16px;">'+c.nom+'</strong>'
+(i===0?' <span style="background:#D8F3DC;color:#2D6A4F;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:700;">RECOMMANDE</span>':'')+'</div>'
+'<div style="font-size:11px;color:var(--text-light);">'+c.saison+'</div></div>'
+'<div style="margin-top:8px;display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;text-align:center;">'
+'<div><div style="font-size:10px;color:#999;">Rendement</div><div style="font-weight:700;">'+c.rendement+' t/ha</div></div>'
+'<div><div style="font-size:10px;color:#999;">Prix</div><div style="font-weight:700;">'+c.prixKg+' FCFA/kg</div></div>'
+'<div><div style="font-size:10px;color:#999;">Revenu estime</div><div style="font-weight:700;color:#2D6A4F;">'+revenuStr+' FCFA</div></div>'
+'</div></div>';});html+='</div>';container.innerHTML=html;container.style.display='block';};window.chercherTechniciens=function(){var pays=document.getElementById('propPays').value||'benin';var region=document.getElementById('propRegion').value||'';var container=document.getElementById('techniciensList');if(!container)return;var techniciens={benin:[{nom:'Agossou Marc',specialite:'Cultures vivrieres, mais, manioc',zone:'Parakou / Borgou',tel:'+229 97 XX XX XX'},{nom:'Adjovi Felicien',specialite:'Maraichage, irrigation',zone:'Bohicon / Zou',tel:'+229 96 XX XX XX'},{nom:'Dossou Achille',specialite:'Cajou, anacarde, sols',zone:'Glazoue / Collines',tel:'+229 95 XX XX XX'},{nom:'Houessou Lydia',specialite:'Cultures de rente, cacao',zone:'Cotonou / Littoral',tel:'+229 94 XX XX XX'}],burkina_faso:[{nom:'Ouedraogo Ibrahim',specialite:'Cereales, mil, sorgho',zone:'Ouagadougou',tel:'+226 70 XX XX XX'},{nom:'Savadogo Mariam',specialite:'Maraichage, oignon',zone:'Bobo-Dioulasso',tel:'+226 71 XX XX XX'}],cote_divoire:[{nom:'Kouame Jean-Pierre',specialite:'Cacao, cafe, hevea',zone:'Abidjan / Sud',tel:'+225 07 XX XX XX'},{nom:'Kone Adama',specialite:'Riz, mais, igname',zone:'Bouake / Centre',tel:'+225 05 XX XX XX'}],mali:[{nom:'Traore Moussa',specialite:'Cereales, riz, coton',zone:'Bamako / Koulikoro',tel:'+223 76 XX XX XX'}],senegal:[{nom:'Diallo Abdoulaye',specialite:'Arachide, mil, riz',zone:'Dakar / Thies',tel:'+221 77 XX XX XX'},{nom:'Ndiaye Fatou',specialite:'Maraichage, tomate, oignon',zone:'Saint-Louis / Niayes',tel:'+221 78 XX XX XX'}],niger:[{nom:'Adamou Harouna',specialite:'Mil, niebe, sorgho',zone:'Niamey / Tillaberi',tel:'+227 96 XX XX XX'}],togo:[{nom:'Mensah Kofi',specialite:'Mais, manioc, igname',zone:'Lome / Maritime',tel:'+228 90 XX XX XX'}],guinee_bissau:[{nom:'Da Silva Carlos',specialite:'Cajou, riz',zone:'Bissau / Biombo',tel:'+245 95 XX XX XX'}]};var liste=techniciens[pays]||techniciens.benin;var html='';liste.forEach(function(t){html+='<div class="card" style="padding:14px;margin-bottom:10px;border-radius:14px;">'
+'<div style="display:flex;align-items:center;gap:12px;">'
+'<div style="width:48px;height:48px;border-radius:50%;background:linear-gradient(135deg,#2D6A4F,#40916C);display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:18px;flex-shrink:0;">'
+t.nom.charAt(0)+'</div>'
+'<div style="flex:1;">'
+'<div style="font-weight:700;font-size:14px;">'+t.nom+'</div>'
+'<div style="font-size:12px;color:var(--text-light);">'+t.specialite+'</div>'
+'<div style="font-size:11px;color:#E8862A;font-weight:600;"><i data-lucide="map-pin" class="lc"></i> '+t.zone+'</div>'
+'</div></div>'
+'<div style="display:flex;gap:8px;margin-top:10px;">'
+'<a href="tel:'+t.tel.replace(/\s/g,'')+'" style="flex:1;padding:10px;background:#2D6A4F;color:#fff;border-radius:10px;text-align:center;text-decoration:none;font-size:13px;font-weight:600;"><i data-lucide="phone" class="lc"></i> Appeler</a>'
+'<a href="https://wa.me/'+t.tel.replace(/[^0-9]/g,'')+'" target="_blank" style="flex:1;padding:10px;background:#25D366;color:#fff;border-radius:10px;text-align:center;text-decoration:none;font-size:13px;font-weight:600;"><i data-lucide="message-circle" class="lc" style="width:14px;height:14px;vertical-align:middle;margin-right:4px;"></i> WhatsApp</a>'
+'</div></div>';});container.innerHTML=html;};window.souscrirePlan=function(plan,montant){var AP=window.AgroPrix;var user=JSON.parse(localStorage.getItem('agroprix_user')||'{}');var fedapayKey=AP&&AP.FEDAPAY_KEY;var keyReady=fedapayKey&&fedapayKey!=='VOTRE_CLE_PUBLIQUE_FEDAPAY_ICI';if(keyReady&&window.FedaPay){var nameParts=(user.nom||user.name||'Client AgroPrix').split(' ');var firstname=nameParts[0]||'Client';var lastname=nameParts.slice(1).join(' ')||'AgroPrix';FedaPay.init({public_key:fedapayKey,transaction:{amount:montant,description:'Abonnement Plan '+plan+' — AgroPrix',custom_metadata:{user_id:user.id||user.user_id||'',plan:plan,source:'agroprix_web'}},customer:{email:user.email||'client@agroprix.app',lastname:lastname,firstname:firstname},onComplete:function(resp){if(resp.reason===FedaPay.CHECKOUT_COMPLETED){onFedapaySuccess(plan,montant,resp);}}}).open();return;}
var fmt=montant.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ');var overlay=document.createElement('div');overlay.id='paymentOverlay';overlay.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.6);z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px;';overlay.innerHTML='<div style="background:#fff;border-radius:20px;padding:24px;max-width:400px;width:100%;">'
+'<div style="text-align:center;margin-bottom:20px;">'
+'<div style="font-size:11px;text-transform:uppercase;letter-spacing:2px;color:#999;">ABONNEMENT</div>'
+'<div style="font-size:24px;font-weight:800;color:#1B4332;margin-top:4px;">Plan '+plan+'</div>'
+'<div style="font-size:28px;font-weight:800;color:#E8862A;margin-top:8px;">'+fmt+' FCFA<span style="font-size:14px;color:#999;font-weight:500;">/mois</span></div>'
+'</div>'
+'<div style="padding:14px;background:#FEF3C7;border-radius:12px;font-size:13px;color:#92400E;margin-bottom:16px;">'
+'<strong>Paiement en ligne non encore active</strong><br>Mobile Money et carte bancaire seront disponibles prochainement. En attendant, souscrivez directement via WhatsApp ci-dessous.'
+'</div>'
+'<a href="https://wa.me/22960000000?text=Je veux souscrire au Plan '+plan+' ('+fmt+' FCFA/mois)" target="_blank" style="display:block;width:100%;padding:14px;background:#25D366;color:#fff;border:none;border-radius:12px;font-size:15px;font-weight:700;cursor:pointer;text-align:center;text-decoration:none;margin-bottom:10px;"><i data-lucide="message-circle" class="lc" style="width:16px;height:16px;vertical-align:middle;margin-right:6px;"></i> Payer via WhatsApp</a>'
+'<button onclick="document.getElementById(\'paymentOverlay\').remove()" style="width:100%;padding:12px;background:none;border:1px solid #ddd;border-radius:12px;font-size:14px;color:#999;cursor:pointer;">Fermer</button>'
+'</div>';document.body.appendChild(overlay);};function onFedapaySuccess(plan,montant,response){var transactionId=response&&response.transaction&&response.transaction.id?response.transaction.id:(response&&response.id?response.id:'N/A');var user=JSON.parse(localStorage.getItem('agroprix_user')||'{}');var previousRole=user.role||'free';user.planPending=plan;user.planPendingSince=new Date().toISOString();user.lastTransactionId=transactionId;localStorage.setItem('agroprix_user',JSON.stringify(user));var AP=window.AgroPrix;var token=localStorage.getItem('agroprix_token');if(AP&&AP.API_BASE){fetch(AP.API_BASE+'/api/subscriptions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({plan:plan,montant:montant,transactionId:transactionId})}).catch(function(){});}
var fmt=montant.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ');var overlay=document.createElement('div');overlay.id='paymentActivationOverlay';overlay.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.6);z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px;';overlay.innerHTML='<div style="background:#fff;border-radius:20px;padding:32px 24px;max-width:400px;width:100%;text-align:center;">'
+'<div id="payIconWrap" style="margin-bottom:16px;">'
+'<div style="width:64px;height:64px;margin:0 auto;border:4px solid #D8F3DC;border-top-color:#2D6A4F;border-radius:50%;animation:spin 1s linear infinite;"></div>'
+'</div>'
+'<div id="payTitle" style="font-size:22px;font-weight:800;color:#1B4332;">Paiement reçu</div>'
+'<div id="paySub" style="font-size:14px;color:#666;margin-top:6px;">Activation du plan <strong>'+plan+'</strong> ('+fmt+' FCFA/mois) en cours…</div>'
+'<div style="font-size:12px;color:#999;margin-top:8px;">Transaction : '+transactionId+'</div>'
+'<div id="payStatus" style="margin-top:16px;padding:12px;background:#FEF3C7;border-radius:12px;font-size:13px;color:#92400E;line-height:1.5;">'
+'Nous attendons la confirmation de FedaPay (webhook). Cela prend habituellement quelques secondes.'
+'</div>'
+'<button id="payCloseBtn" onclick="document.getElementById(\'paymentActivationOverlay\').remove()" style="width:100%;margin-top:16px;padding:14px;background:linear-gradient(135deg,#1B4332,#2D6A4F);color:#fff;border:none;border-radius:14px;font-size:15px;font-weight:700;cursor:pointer;">OK, continuer</button>'
+'</div>'
+'<style>@keyframes spin{to{transform:rotate(360deg)}}</style>';document.body.appendChild(overlay);pollAuthMeForRoleUpgrade({previousRole:previousRole,expectedPlan:plan,maxAttempts:12,intervalMs:5000,onUpgrade:function(newUser){var wrap=document.getElementById('payIconWrap');var title=document.getElementById('payTitle');var sub=document.getElementById('paySub');var status=document.getElementById('payStatus');if(wrap)wrap.innerHTML='<i data-lucide="check-circle" style="width:64px;height:64px;color:#2D6A4F;" class="lc"></i>';if(title)title.textContent='Plan activé !';if(sub)sub.innerHTML='Plan <strong>'+plan+'</strong> actif — '+fmt+' FCFA/mois';if(status){status.style.background='#D8F3DC';status.style.color='#1B4332';status.innerHTML='Toutes les fonctionnalités sont maintenant disponibles.';}
if(window.lucide&&lucide.createIcons)lucide.createIcons();},onTimeout:function(){var status=document.getElementById('payStatus');if(status){status.innerHTML='<strong>Paiement bien reçu</strong> — l\'activation prend un peu plus de temps que prévu. '
+'Rafraîchissez la page dans quelques minutes. Si le plan n\'est toujours pas actif, '
+'contactez support@agroprix.app avec la référence : <code>'+transactionId+'</code>';}}});}
function pollAuthMeForRoleUpgrade(opts){var AP=window.AgroPrix;var token=localStorage.getItem('agroprix_token');if(!AP||!AP.API_BASE||!token){if(opts&&opts.onTimeout)opts.onTimeout();return;}
var attempts=0;var max=opts.maxAttempts||12;var interval=opts.intervalMs||5000;var previousRole=opts.previousRole||'free';function tick(){attempts++;fetch(AP.API_BASE+'/api/auth/me',{headers:{'Authorization':'Bearer '+token},cache:'no-store'}).then(function(r){return r.ok?r.json():null;}).then(function(body){var u=body&&body.utilisateur;if(u&&u.role&&u.role!==previousRole&&u.role!=='free'){try{var stored=JSON.parse(localStorage.getItem('agroprix_user')||'{}');stored.role=u.role;stored.rate_limit=u.rate_limit;stored.planPending=null;stored.planPendingSince=null;localStorage.setItem('agroprix_user',JSON.stringify(stored));}catch(e){}
if(opts.onUpgrade)opts.onUpgrade(u);return;}
if(attempts>=max){if(opts.onTimeout)opts.onTimeout();return;}
setTimeout(tick,interval);}).catch(function(){if(attempts>=max){if(opts.onTimeout)opts.onTimeout();return;}
setTimeout(tick,interval);});}
setTimeout(tick,2000);}
window.pollAuthMeForRoleUpgrade=pollAuthMeForRoleUpgrade;