/*! AgroPrix auth.js - generated from auth.js.src on 2026-04-18 - DO NOT EDIT; edit the .src file and run `python build_js.py` */
(function(AP){'use strict';var TOKEN_KEY='agroprix_token';var USER_KEY='agroprix_user';function getToken(){return localStorage.getItem(TOKEN_KEY);}
function getUser(){try{var raw=localStorage.getItem(USER_KEY);return raw?JSON.parse(raw):null;}catch(e){return null;}}
function saveSession(token,user){localStorage.setItem(TOKEN_KEY,token);localStorage.setItem(USER_KEY,JSON.stringify(user));updateAuthUI(user);}
function clearSession(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);try{localStorage.removeItem('agroprix_farmer_profile');localStorage.removeItem('agroprix_streak');localStorage.removeItem('agroprix_points');localStorage.removeItem('agroprix_badges');localStorage.removeItem('agroprix_last_visit');}catch(e){}
updateAuthUI(null);}
function isLoggedIn(){return!!getToken();}
function authFetch(url,options){options=options||{};options.headers=options.headers||{};options.headers['Content-Type']='application/json';var token=getToken();if(token){options.headers['Authorization']='Bearer '+token;}
return fetch(AP.API_BASE+url,options);}
function register(email,password,name,phone,country){var body={email:email,password:password,name:name};if(phone)body.phone=phone;if(country)body.country=country;return authFetch('/api/auth/register',{method:'POST',body:JSON.stringify(body)}).then(function(r){if(!r.ok)return r.json().then(function(e){throw e;});return r.json();}).then(function(data){saveSession(data.token,data.utilisateur);return data;});}
function login(email,password){return authFetch('/api/auth/login',{method:'POST',body:JSON.stringify({email:email,password:password})}).then(function(r){if(!r.ok)return r.json().then(function(e){throw e;});return r.json();}).then(function(data){saveSession(data.token,data.utilisateur);return data;});}
function fetchProfile(){return authFetch('/api/auth/me').then(function(r){if(!r.ok){clearSession();throw new Error('Session expirée');}
return r.json();}).then(function(data){var user=data.utilisateur;localStorage.setItem(USER_KEY,JSON.stringify(user));updateAuthUI(user);return user;});}
function logout(){clearSession();showAuthScreen('login');}
function updateAuthUI(user){var nameEl=document.querySelector('.user-name');var roleEl=document.querySelector('.user-role');var avatarEl=document.querySelector('.sidebar-footer .avatar');if(user){if(nameEl)nameEl.textContent=user.nom||user.name||'Utilisateur';if(roleEl){var roleLabels={free:'Plan Gratuit',pro:'Plan Pro',expert:'Plan Expert',admin:'Administrateur'};roleEl.textContent=roleLabels[user.role]||'Plan Gratuit';}
if(avatarEl){var initials=(user.nom||user.name||'U').split(' ').map(function(w){return w[0];}).join('').toUpperCase().substring(0,2);avatarEl.textContent=initials;}
var profileName=document.getElementById('profileName');var profileEmail=document.getElementById('profileEmail');var profileCountry=document.getElementById('profileCountry');var profilePlan=document.getElementById('profilePlan');if(profileName)profileName.textContent=user.nom||user.name||'—';if(profileEmail)profileEmail.textContent=user.email||'—';if(profileCountry)profileCountry.textContent=user.pays||user.country||'—';if(profilePlan){var planLabels={free:'Gratuit',pro:'Pro · 2 900 FCFA/mois',expert:'Expert · 14 900 FCFA/mois',admin:'Administrateur'};profilePlan.textContent=planLabels[user.role]||'Gratuit';}
var authScreen=document.getElementById('authScreen');var appContainer=document.getElementById('appContainer');if(authScreen)authScreen.style.display='none';if(appContainer)appContainer.style.display='';}}
function showAuthScreen(mode){mode=mode||'login';var authScreen=document.getElementById('authScreen');var appContainer=document.getElementById('appContainer');if(authScreen)authScreen.style.display='flex';if(appContainer)appContainer.style.display='none';var loginForm=document.getElementById('loginForm');var registerForm=document.getElementById('registerForm');var loginTab=document.getElementById('authTabLogin');var registerTab=document.getElementById('authTabRegister');if(mode==='login'){if(loginForm)loginForm.style.display='block';if(registerForm)registerForm.style.display='none';if(loginTab)loginTab.classList.add('active');if(registerTab)registerTab.classList.remove('active');}else{if(loginForm)loginForm.style.display='none';if(registerForm)registerForm.style.display='block';if(loginTab)loginTab.classList.remove('active');if(registerTab)registerTab.classList.add('active');}}
function handleLogin(e){if(e)e.preventDefault();var email=document.getElementById('loginEmail').value.trim();var password=document.getElementById('loginPassword').value;var errorEl=document.getElementById('loginError');var btn=document.getElementById('loginBtn');if(!email||!password){if(errorEl)errorEl.textContent='Veuillez remplir tous les champs.';return;}
if(btn){btn.disabled=true;btn.textContent='Connexion...';}
if(errorEl)errorEl.textContent='';login(email,password).then(function(){if(btn){btn.disabled=false;btn.textContent='Se connecter';}}).catch(function(err){if(btn){btn.disabled=false;btn.textContent='Se connecter';}
var msg=(err&&err.detail)?err.detail:'Erreur de connexion';if(errorEl)errorEl.textContent=msg;});}
function handleRegister(e){if(e)e.preventDefault();var name=document.getElementById('regName').value.trim();var email=document.getElementById('regEmail').value.trim();var phone=document.getElementById('regPhone').value.trim();var country=document.getElementById('regCountry').value;var password=document.getElementById('regPassword').value;var confirm=document.getElementById('regConfirm').value;var errorEl=document.getElementById('registerError');var btn=document.getElementById('registerBtn');if(!name||!email||!password){if(errorEl)errorEl.textContent='Veuillez remplir les champs obligatoires.';return;}
if(password.length<6){if(errorEl)errorEl.textContent='Le mot de passe doit contenir au moins 6 caractères.';return;}
if(password!==confirm){if(errorEl)errorEl.textContent='Les mots de passe ne correspondent pas.';return;}
if(btn){btn.disabled=true;btn.textContent='Création...';}
if(errorEl)errorEl.textContent='';register(email,password,name,phone,country).then(function(){if(btn){btn.disabled=false;btn.textContent='Créer mon compte';}}).catch(function(err){if(btn){btn.disabled=false;btn.textContent='Créer mon compte';}
var msg=(err&&err.detail)?err.detail:'Erreur lors de la création';if(errorEl)errorEl.textContent=msg;});}
function initAuth(){var token=getToken();var user=getUser();if(token&&user){updateAuthUI(user);if(user.demo===true||token==='demo-token-v6'){return;}
fetchProfile().catch(function(){showAuthScreen('login');});}else{showAuthScreen('login');}}
AP.auth={getToken:getToken,getUser:getUser,isLoggedIn:isLoggedIn,login:login,register:register,logout:logout,fetchProfile:fetchProfile,initAuth:initAuth,showAuthScreen:showAuthScreen,handleLogin:handleLogin,handleRegister:handleRegister};window.handleLogin=handleLogin;window.handleRegister=handleRegister;window.showAuthScreen=showAuthScreen;window.logout=logout;})(window.AgroPrix);