/*! AgroPrix marketplace.js - generated from marketplace.js.src on 2026-06-27 - DO NOT EDIT; edit the .src file and run `python build_js.py` */
(function(AP){'use strict';var currentTab='marche';var OFFERS_KEY='agroprix_marketplace_offers';var DEMANDS_KEY='agroprix_marketplace_demands';var API_BASE=(AP&&AP.API_BASE)?AP.API_BASE:'';var _catFilters={category:'',type:'',q:''};var _catCountry='';var _notifBox='all';function _apiBase(){return AP.API_BASE||'';}
function _userIso3(){try{return(AP.countryMeta[getUserCountry()]||{}).iso3||'';}catch(e){return'';}}
function _productName(l){var k=l.culture||'';return(AP.cultureNames&&AP.cultureNames[k])?AP.cultureNames[k]:String(k).replace(/_/g,' ');}
function _qtyLabel(kg){if(kg==null)return'';return kg>=1000?(Math.round(kg/100)/10)+' t':Math.round(kg)+' kg';}
var _formCategory='cultures';var FAM_LABELS={cultures:'Cultures',intrants:'Intrants',equipements:'Équipements',services:'Services'};var PRODUCTS={intrants:{engrais_npk:'Engrais NPK',engrais_uree:'Urée',engrais_dap:'DAP',compost:'Compost',semences_mais:'Semences maïs',semences_riz:'Semences riz',semences_maraichage:'Semences maraîchage',herbicide:'Herbicide',insecticide:'Insecticide',fongicide:'Fongicide'},equipements:{tracteur:'Tracteur',motoculteur:'Motoculteur',pulverisateur:'Pulvérisateur',kit_irrigation:"Kit d'irrigation",batteuse:'Batteuse',sechoir:'Séchoir',sacs_stockage:'Sacs de stockage'},services:{labour:'Labour',transport:'Transport',stockage:'Stockage',conseil_agronomique:'Conseil agronomique',main_oeuvre:"Main d'œuvre",location_materiel:'Location de matériel'}};function _productsFor(cat){return cat==='cultures'?(AP.cultureNames||{}):(PRODUCTS[cat]||{});}
var UNIT_KG={kg:1,tonnes:1000,sacs:50,paniers:25};function _uploadPhoto(file){return fetch(_apiBase()+'/api/marketplace/photos/sign',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,content_type:file.type})}).then(function(r){return r.ok?r.json():null;}).then(function(s){if(!s||!s.configured||!s.upload_url)return null;return fetch(s.upload_url,{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file}).then(function(up){return up.ok?s.public_url:null;});}).catch(function(){return null;});}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function _authHeaders(){var h={'Content-Type':'application/json'};var legacy=localStorage.getItem('agroprix_token');if(legacy)h['Authorization']='Bearer '+legacy;return h;}
function _fetchOpts(extra){var o=extra||{};o.credentials='include';return o;}
function _fromBackend(row){return{id:row.id!=null?String(row.id):(Date.now().toString(36)),type:row.type,crop:row.crop,cropName:row.crop_name||row.crop,quantity:row.quantity,unit:row.unit||'tonnes',price:row.type==='buy'?undefined:row.price,maxPrice:row.type==='buy'?row.price:undefined,priceUnit:row.price_unit||'FCFA/kg',market:row.market||'',description:row.description||'',seller:row.type==='sell'?(row.seller||'Utilisateur'):undefined,buyer:row.type==='buy'?(row.seller||'Utilisateur'):undefined,phone:row.phone||'',country:row.country||'benin',date:row.created_at||new Date().toISOString(),status:row.status||'active'};}
function _toBackend(item){return{type:item.type,crop:item.crop,crop_name:item.cropName||item.crop,quantity:Number(item.quantity)||0,unit:item.unit||'tonnes',price:Number(item.type==='buy'?item.maxPrice:item.price)||0,price_unit:item.priceUnit||'FCFA/kg',market:item.market||'',description:item.description||'',phone:item.phone||'',country:item.country||(AP.auth&&AP.auth.getUser&&(AP.auth.getUser().pays||AP.auth.getUser().country))||'benin'};}
function getOffers(){try{return JSON.parse(localStorage.getItem(OFFERS_KEY)||'[]');}catch(e){return[];}}
function getDemands(){try{return JSON.parse(localStorage.getItem(DEMANDS_KEY)||'[]');}catch(e){return[];}}
function saveOffer(offer){var offers=getOffers();offers.unshift(offer);localStorage.setItem(OFFERS_KEY,JSON.stringify(offers));if(API_BASE){fetch(API_BASE+'/api/market/offers',_fetchOpts({method:'POST',headers:_authHeaders(),body:JSON.stringify(_toBackend(offer))})).then(function(r){if(!r.ok)console.warn('[marketplace] saveOffer backend HTTP',r.status);else setTimeout(syncFromBackend,500);}).catch(function(e){console.warn('[marketplace] saveOffer backend fail',e);});}}
function saveDemand(demand){var demands=getDemands();demands.unshift(demand);localStorage.setItem(DEMANDS_KEY,JSON.stringify(demands));if(API_BASE){fetch(API_BASE+'/api/market/offers',_fetchOpts({method:'POST',headers:_authHeaders(),body:JSON.stringify(_toBackend(demand))})).then(function(r){if(!r.ok)console.warn('[marketplace] saveDemand backend HTTP',r.status);else setTimeout(syncFromBackend,500);}).catch(function(e){console.warn('[marketplace] saveDemand backend fail',e);});}}
function syncFromBackend(cb){if(!API_BASE){if(cb)cb();return;}
fetch(API_BASE+'/api/market/offers?offer_type=sell',_fetchOpts({headers:_authHeaders()})).then(function(r){return r.ok?r.json():null;}).then(function(data){if(data&&Array.isArray(data.offers)){localStorage.setItem(OFFERS_KEY,JSON.stringify(data.offers.map(_fromBackend)));}
return fetch(API_BASE+'/api/market/offers?offer_type=buy',_fetchOpts({headers:_authHeaders()}));}).then(function(r){return r&&r.ok?r.json():null;}).then(function(data){if(data&&Array.isArray(data.offers)){localStorage.setItem(DEMANDS_KEY,JSON.stringify(data.offers.map(_fromBackend)));}
if(cb)cb();}).catch(function(){if(cb)cb();});}
function getUserCountry(){var user=AP.auth?AP.auth.getUser():null;return(user&&(user.pays||user.country))||'benin';}
function getMarkets(){return(AP.marketsByCountry&&AP.marketsByCountry[getUserCountry()])||[];}
function getUserName(){var user=AP.auth?AP.auth.getUser():null;return(user&&(user.nom||user.name))||'Utilisateur';}
function formatFCFA(n){if(!n)return'—';return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ')+' FCFA';}
function timeAgo(iso){var diff=Date.now()-new Date(iso).getTime();var hours=Math.floor(diff/3600000);if(hours<1)return'A l\'instant';if(hours<24)return'Il y a '+hours+'h';var days=Math.floor(hours/24);if(days<7)return'Il y a '+days+'j';return new Date(iso).toLocaleDateString('fr');}
function generateId(){return Date.now().toString(36)+Math.random().toString(36).substr(2,6);}
function seedDemoData(){return;}
function findMatches(){var offers=getOffers().filter(function(o){return o.status==='active';});var demands=getDemands().filter(function(d){return d.status==='active';});var matches=[];demands.forEach(function(d){offers.forEach(function(o){if(o.crop===d.crop){var priceMatch=true;matches.push({offer:o,demand:d,cropMatch:true,priceMatch:priceMatch});}});});return matches;}
function render(){var html='';html+='<div style="display:flex;gap:0;margin-bottom:16px;border-bottom:2px solid var(--border);">';[{id:'marche',label:'<i data-lucide="store" class="lc"></i> Marche'},{id:'vendre',label:'<i data-lucide="package" class="lc"></i> Vendre'},{id:'acheter',label:'<i data-lucide="shopping-cart" class="lc"></i> Acheter'},{id:'mes-transactions',label:'<i data-lucide="clipboard-list" class="lc"></i> Mes annonces'},{id:'notifs',label:'<i data-lucide="bell" class="lc"></i> Notifs'}].forEach(function(t){var active=currentTab===t.id;html+='<button data-action="mkt-set-tab" data-tab="'+t.id+'" style="flex:1;padding:10px;font-size:12px;font-weight:'+(active?'700':'500')+';color:'+(active?'var(--green)':'var(--text-light)')+';background:none;border:none;border-bottom:'+(active?'3px solid var(--green)':'3px solid transparent')+';cursor:pointer;font-family:inherit;">'+t.label+'</button>';});html+='</div>';if(currentTab==='marche')html+=renderMarche();else if(currentTab==='vendre')html+=renderForm('sell');else if(currentTab==='acheter')html+=renderForm('buy');else if(currentTab==='mes-transactions')html+=renderMesAnnonces();else if(currentTab==='notifs')html+=renderNotifs();var container=document.getElementById('marketplaceContent');if(container)container.innerHTML=html;if(currentTab==='marche')loadCatalogue();else if(currentTab==='notifs')loadNotifs();}
function renderMarche(){function chip(action,val,label,active){return'<button data-action="'+action+'" data-value="'+val+'" style="padding:6px 12px;border-radius:20px;border:1px solid '+(active?'#2D6A4F':'#ccc')+';background:'+(active?'#2D6A4F':'#fff')+';color:'+(active?'#fff':'#555')+';font-size:11px;font-weight:600;cursor:pointer;">'+label+'</button>';}
var fams=[['','Tout'],['cultures','Cultures'],['intrants','Intrants'],['equipements','Équip.'],['services','Services']];var types=[['','Tout'],['offre','Offres'],['demande','Demandes']];var html='<div style="background:linear-gradient(135deg,#1B4332,#2D6A4F);border-radius:18px;padding:16px;color:#fff;margin-bottom:14px;text-align:center;">'
+'<div style="font-size:18px;font-weight:800;"><i data-lucide="store" class="lc"></i> Place de Marché</div>'
+'<div style="font-size:11px;opacity:0.85;">Catalogue — offres &amp; demandes</div></div>';html+='<div style="display:flex;gap:6px;margin-bottom:10px;">'
+'<input id="mktSearch" type="text" placeholder="Rechercher un produit…" value="'+esc(_catFilters.q)+'" style="flex:1;padding:9px 12px;border:1px solid #E0E0E0;border-radius:10px;font-size:13px;">'
+'<button data-action="mkt-cat-search" style="padding:9px 14px;background:#2D6A4F;color:#fff;border:none;border-radius:10px;font-size:13px;font-weight:600;cursor:pointer;"><i data-lucide="search" class="lc"></i></button></div>';html+='<div style="display:flex;gap:5px;flex-wrap:wrap;margin-bottom:8px;">'+fams.map(function(f){return chip('mkt-cat-fam',f[0],f[1],_catFilters.category===f[0]);}).join('')+'</div>';html+='<div style="display:flex;gap:5px;flex-wrap:wrap;margin-bottom:12px;">'+types.map(function(t){return chip('mkt-cat-type',t[0],t[1],_catFilters.type===t[0]);}).join('')
+chip('mkt-cat-country','toggle',(_catCountry?'Mon pays':'Tous pays'),!!_catCountry)+'</div>';html+='<div id="mktCatalog"></div>';return html;}
function _catCard(l){var isSell=l.listing_type==='offre';var typeBadge='<span style="font-size:9px;font-weight:700;padding:2px 7px;border-radius:6px;background:'+(isSell?'#EAF3DE;color:#27500A':'#FAEEDA;color:#854F0B')+';">'+(isSell?'Offre':'Demande')+'</span>';var verified=l.seller_verified?'<span style="font-size:9px;background:#D8F3DC;color:#1B4332;padding:2px 6px;border-radius:6px;font-weight:700;">✓ Vérifié</span>':'';var loc=esc(l.market_name||l.region||l.country_iso3||'—');var deliv=(!isSell&&l.delivery_date)?('<div style="font-size:10px;color:#E8862A;margin-top:2px;">Livraison : '+esc(l.delivery_date)+'</div>'):'';var desc=l.description?('<div style="font-size:12px;color:#666;margin-top:6px;">'+esc(String(l.description).slice(0,120))+'</div>'):'';return'<div class="card" style="margin-bottom:12px;padding:14px;">'
+'<div style="display:flex;justify-content:space-between;align-items:start;">'
+'<div><div style="font-size:15px;font-weight:800;color:#333;"><i data-lucide="wheat" class="lc" style="width:16px;height:16px;vertical-align:-2px;"></i> '+esc(_productName(l))+'</div>'
+'<div style="font-size:11px;color:#888;margin-top:2px;">'+_qtyLabel(l.quantity_kg)+' · '+loc+'</div></div>'
+'<div style="text-align:right;">'+typeBadge+'<div style="font-size:14px;font-weight:800;color:#2D6A4F;margin-top:4px;">'+formatFCFA(l.unit_price_fcfa)+'/kg</div></div>'
+'</div>'+deliv+desc
+(verified?('<div style="margin-top:6px;">'+verified+'</div>'):'')
+'<button data-action="mkt-contact" data-id="'+l.id+'" style="display:block;width:100%;margin-top:10px;padding:10px;background:#25D366;color:#fff;border:none;border-radius:10px;font-size:13px;font-weight:700;cursor:pointer;"><i data-lucide="message-circle" class="lc" style="width:15px;height:15px;vertical-align:-2px;"></i> Contacter</button>'
+'</div>';}
function loadCatalogue(){var box=document.getElementById('mktCatalog');if(!box)return;box.innerHTML='<div style="text-align:center;padding:24px;color:#999;font-size:13px;">Chargement du catalogue…</div>';var qs=['limit=100'];if(_catFilters.category)qs.push('category='+encodeURIComponent(_catFilters.category));if(_catFilters.type)qs.push('type='+encodeURIComponent(_catFilters.type));if(_catCountry)qs.push('country='+encodeURIComponent(_catCountry));fetch(_apiBase()+'/api/marketplace/listings?'+qs.join('&'),{credentials:'include'}).then(function(r){return r.ok?r.json():{listings:[]};}).then(function(d){var items=(d&&d.listings)||[];var q=(_catFilters.q||'').toLowerCase().trim();if(q)items=items.filter(function(l){return(_productName(l)+' '+(l.market_name||'')+' '+(l.region||'')+' '+(l.description||'')).toLowerCase().indexOf(q)>=0;});if(!items.length){box.innerHTML='<div class="card" style="padding:28px;text-align:center;"><div style="font-size:40px;"><i data-lucide="store" class="lc"></i></div><h3 style="color:#666;">Aucune annonce</h3><p style="font-size:12px;color:#999;">Ajustez vos filtres ou publiez la première annonce.</p></div>';}else{box.innerHTML=items.map(_catCard).join('')+'<div style="text-align:center;padding:12px;font-size:12px;color:#999;">'+items.length+' annonce(s)</div>';}
if(window.lucide){try{window.lucide.createIcons();}catch(e){}}}).catch(function(){box.innerHTML='<div class="card" style="padding:20px;text-align:center;color:#999;font-size:13px;">Catalogue indisponible. Réessayez.</div>';});}
function contactListing(id){fetch(_apiBase()+'/api/marketplace/listings/'+id+'/contact',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:null})}).then(function(r){if(r.status===401||r.status===403){alert('Connectez-vous pour contacter cette annonce.');return null;}
if(!r.ok)throw new Error('http');return r.json();}).then(function(d){if(!d)return;if(d.duplicate)alert('Vous avez déjà envoyé une demande pour cette annonce.');else alert('Demande de contact envoyée ! Vous serez mis en relation dès acceptation.');}).catch(function(){alert('Impossible d\'envoyer la demande pour le moment.');});}
function renderNotifs(){function tab(val,label){var on=(_notifBox===val);return'<button data-action="mkt-notif-box" data-value="'+val+'" style="flex:1;padding:8px;border-radius:8px;border:1px solid '+(on?'#2D6A4F':'#ccc')+';background:'+(on?'#2D6A4F':'#fff')+';color:'+(on?'#fff':'#555')+';font-size:11px;font-weight:600;cursor:pointer;">'+label+'</button>';}
return'<div style="display:flex;gap:6px;margin-bottom:12px;">'+tab('all','Toutes')+tab('acheteur','Acheteur')+tab('vendeur','Vendeur')+'</div><div id="mktNotifs"></div>';}
function _notifCard(n){var l=n.listing||{};var prod=l.culture?_productName({culture:l.culture}):'—';var roleBadge='<span style="font-size:9px;font-weight:700;padding:2px 6px;border-radius:5px;background:'+(n.requester_role==='buyer'?'#EAF3DE;color:#27500A':'#FAEEDA;color:#854F0B')+';">'+(n.requester_role==='buyer'?'Acheteur':'Vendeur')+'</span>';var verified=n.requester_verified?' <i data-lucide="rosette-discount-check" class="lc" style="width:12px;height:12px;color:#2D6A4F;vertical-align:-2px;"></i>':'';var when=n.created_at?timeAgo(n.created_at):'';var summary=esc(prod)+(l.quantity_kg?(' · '+_qtyLabel(l.quantity_kg)):'')+(l.market_name?(' · '+esc(l.market_name)):'');var actions;if(n.status==='pending'){actions='<div style="display:flex;gap:6px;margin-top:8px;">'
+'<button data-action="mkt-notif-accept" data-id="'+n.id+'" style="flex:1;padding:8px;background:#25D366;color:#fff;border:none;border-radius:8px;font-size:11px;font-weight:700;cursor:pointer;"><i data-lucide="message-circle" class="lc" style="width:13px;height:13px;vertical-align:-2px;"></i> Accepter</button>'
+'<button data-action="mkt-notif-refuse" data-id="'+n.id+'" style="flex:1;padding:8px;background:#fff;border:1px solid #E0E0E0;color:#666;border-radius:8px;font-size:11px;font-weight:600;cursor:pointer;">Refuser</button></div>';}else if(n.status==='accepted'){actions='<div style="margin-top:8px;font-size:11px;color:#2D6A4F;font-weight:600;"><i data-lucide="check" class="lc" style="width:12px;height:12px;vertical-align:-2px;"></i> Acceptée — mise en relation effectuée.</div>';}else{actions='<div style="margin-top:8px;font-size:11px;color:#999;">Refusée.</div>';}
return'<div class="card" style="margin-bottom:10px;padding:12px;">'
+'<div style="display:flex;justify-content:space-between;align-items:center;"><span>'+roleBadge+'</span><span style="font-size:9px;color:#999;">'+when+'</span></div>'
+'<div style="font-size:12px;color:#333;margin-top:6px;"><b>'+esc(n.requester_name||'Demandeur')+'</b>'+verified+' — '+summary+'</div>'
+(n.message?('<div style="font-size:11px;color:#666;margin-top:4px;font-style:italic;">« '+esc(n.message)+' »</div>'):'')
+actions+'</div>';}
function loadNotifs(){var box=document.getElementById('mktNotifs');if(!box)return;box.innerHTML='<div style="text-align:center;padding:24px;color:#999;font-size:13px;">Chargement…</div>';fetch(_apiBase()+'/api/marketplace/me/contact-requests?box='+encodeURIComponent(_notifBox),{credentials:'include'}).then(function(r){if(r.status===401||r.status===403)return{_unauth:true};return r.ok?r.json():{requests:[]};}).then(function(d){if(d&&d._unauth){box.innerHTML='<div class="card" style="padding:24px;text-align:center;color:#999;font-size:13px;">Connectez-vous pour voir vos notifications.</div>';return;}
var items=(d&&d.requests)||[];if(!items.length){box.innerHTML='<div class="card" style="padding:28px;text-align:center;"><div style="font-size:40px;"><i data-lucide="bell-off" class="lc"></i></div><h3 style="color:#666;">Aucune notification</h3><p style="font-size:12px;color:#999;">Les demandes de contact reçues apparaîtront ici.</p></div>';}else{box.innerHTML=items.map(_notifCard).join('');}
if(window.lucide){try{window.lucide.createIcons();}catch(e){}}}).catch(function(){box.innerHTML='<div class="card" style="padding:20px;text-align:center;color:#999;font-size:13px;">Notifications indisponibles.</div>';});}
function respondContact(id,action){fetch(_apiBase()+'/api/marketplace/contact-requests/'+id+'/'+action,{method:'POST',credentials:'include'}).then(function(r){if(r.status===401||r.status===403){alert('Connectez-vous.');return null;}
if(!r.ok)throw new Error('http');return r.json();}).then(function(d){if(!d)return;if(action==='accept'&&d.whatsapp_url){window.open(d.whatsapp_url,'_blank');}
loadNotifs();}).catch(function(){alert('Action impossible pour le moment.');});}
function renderForm(type){var isSell=type==='sell';var markets=getMarkets();var products=_productsFor(_formCategory);var html='';html+='<div class="card" style="padding:16px;">'
+'<div class="card-title"><span class="icon">'+(isSell?'<i data-lucide="package" class="lc"></i>':'<i data-lucide="shopping-cart" class="lc"></i>')+'</span> '+(isSell?'Publier une offre de vente':'Publier une demande d\'achat')+'</div>'
+'<p style="font-size:12px;color:var(--text-light);margin-bottom:12px;">'+(isSell?'Proposez vos produits aux acheteurs.':'Decrivez ce que vous recherchez.')+'</p>';html+='<div class="form-group" style="margin-bottom:10px;"><label class="form-label" style="font-weight:600;">Famille</label>'
+'<div style="display:flex;gap:5px;flex-wrap:wrap;margin-top:4px;">';Object.keys(FAM_LABELS).forEach(function(cat){var on=(_formCategory===cat);html+='<button data-action="mkt-form-fam" data-value="'+cat+'" data-type="'+type+'" style="padding:6px 11px;border-radius:18px;border:1px solid '+(on?'#2D6A4F':'#ccc')+';background:'+(on?'#2D6A4F':'#fff')+';color:'+(on?'#fff':'#555')+';font-size:11px;font-weight:600;cursor:pointer;">'+FAM_LABELS[cat]+'</button>';});html+='</div></div>';html+='<div class="form-group" style="margin-bottom:12px;">'
+'<label class="form-label" style="font-weight:600;">Produit</label>'
+'<select id="mpCrop" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;">';Object.keys(products).forEach(function(k){html+='<option value="'+k+'">'+products[k]+'</option>';});html+='</select></div>';html+='<div style="display:grid;grid-template-columns:2fr 1fr;gap:12px;margin-bottom:12px;">'
+'<div class="form-group"><label class="form-label" style="font-weight:600;">Quantite</label>'
+'<input type="number" id="mpQuantity" placeholder="Ex: 10" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;" min="0"></div>'
+'<div class="form-group"><label class="form-label" style="font-weight:600;">Unite</label>'
+'<select id="mpUnit" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;">'
+'<option value="kg">kg</option><option value="tonnes" selected>tonnes</option><option value="sacs">sacs</option><option value="paniers">paniers</option>'
+'</select></div></div>';html+='<div class="form-group" style="margin-bottom:12px;">'
+'<label class="form-label" style="font-weight:600;">'+(isSell?'Prix demande (FCFA/kg)':'Prix maximum (FCFA/kg)')+'</label>'
+'<input type="number" id="mpPrice" placeholder="Ex: 265" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;" min="0">'
+'</div>';html+='<div class="form-group" style="margin-bottom:12px;">'
+'<label class="form-label" style="font-weight:600;">Lieu / Marche</label>'
+'<select id="mpMarket" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;">';markets.forEach(function(m){html+='<option value="'+m.name+'">'+m.name+'</option>';});html+='<option value="Autre">Autre</option></select></div>';if(!isSell){html+='<div class="form-group" style="margin-bottom:12px;">'
+'<label class="form-label" style="font-weight:600;">Date de livraison souhaitee</label>'
+'<input type="date" id="mpDeliveryDate" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;"></div>';}
html+='<div class="form-group" style="margin-bottom:12px;">'
+'<label class="form-label" style="font-weight:600;">Description</label>'
+'<textarea id="mpDescription" rows="3" placeholder="'+(isSell?'Qualite, disponibilite, conditions...':'Specifications, deadline, conditions...')+'" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;font-family:inherit;resize:vertical;"></textarea>'
+'</div>';html+='<div class="form-group" style="margin-bottom:16px;">'
+'<label class="form-label" style="font-weight:600;"><i data-lucide="camera" class="lc" style="width:14px;height:14px;vertical-align:-2px;"></i> Photo (optionnelle)</label>'
+'<input type="file" id="mpPhoto" accept="image/*" style="width:100%;padding:8px;border:1px solid var(--border);border-radius:8px;font-family:inherit;font-size:12px;"></div>';html+='<button class="btn-analyse" id="mpPublishBtn" style="width:100%;font-size:14px;padding:12px;" data-action="mkt-publish" data-type="'+type+'">'
+'<i data-lucide="megaphone" class="lc"></i> Publier '+(isSell?'l\'offre':'la demande')+'</button>';html+='<div id="mpSuccess" style="display:none;margin-top:12px;padding:10px;background:#d1fae5;border-radius:8px;text-align:center;font-size:13px;color:#1B4332;font-weight:600;"></div>';html+='</div>';return html;}
function renderMesAnnonces(){var offers=getOffers();var demands=getDemands();var userName=getUserName();var html='';var myOffers=offers.filter(function(o){return o.seller===userName;});var myDemands=demands.filter(function(d){return d.buyer===userName;});if(myOffers.length===0&&myDemands.length===0){html+='<div class="card" style="padding:32px;text-align:center;">'
+'<div style="font-size:48px;margin-bottom:12px;"><i data-lucide="clipboard-list" class="lc"></i></div>'
+'<h3 style="color:var(--text-light);">Aucune annonce</h3>'
+'<p style="font-size:13px;color:var(--text-muted);">Publiez une offre ou une demande pour la retrouver ici.</p>'
+'</div>';return html;}
if(myOffers.length>0){html+='<div class="card" style="padding:16px;margin-bottom:16px;">'
+'<div class="card-title"><span class="icon"><i data-lucide="package" class="lc"></i></span> Mes offres de vente ('+myOffers.length+')</div>';myOffers.forEach(function(o){html+='<div style="padding:8px 0;border-bottom:1px solid var(--border);">'
+'<div style="display:flex;justify-content:space-between;align-items:center;">'
+'<div><strong>'+esc(o.quantity)+esc(o.unit)+' '+esc(o.cropName)+'</strong> — '+esc(o.market)+'</div>'
+'<span style="font-size:13px;font-weight:700;color:var(--green);">'+formatFCFA(o.price)+'/kg</span>'
+'</div>'
+'<div style="font-size:11px;color:var(--text-light);margin-top:2px;">'+timeAgo(o.date)+' — '+(o.status==='active'?'<span style="color:#10B981;">●</span> Active':'<span style="color:#9CA3AF;">●</span> Terminee')+'</div>'
+'</div>';});html+='</div>';}
if(myDemands.length>0){html+='<div class="card" style="padding:16px;">'
+'<div class="card-title"><span class="icon"><i data-lucide="shopping-cart" class="lc"></i></span> Mes demandes d\'achat ('+myDemands.length+')</div>';myDemands.forEach(function(d){html+='<div style="padding:8px 0;border-bottom:1px solid var(--border);">'
+'<div style="display:flex;justify-content:space-between;align-items:center;">'
+'<div><strong>'+esc(d.quantity)+esc(d.unit)+' '+esc(d.cropName)+'</strong> — '+esc(d.market)+'</div>'
+'<span style="font-size:13px;font-weight:700;color:var(--blue,#3b82f6);">Max '+esc(d.maxPrice)+' '+esc(d.priceUnit)+'</span>'
+'</div>'
+'<div style="font-size:11px;color:var(--text-light);margin-top:2px;">'+timeAgo(d.date)+' — '+(d.status==='active'?'<span style="color:#10B981;">●</span> Active':'<span style="color:#9CA3AF;">●</span> Terminee')+'</div>'
+'</div>';});html+='</div>';}
return html;}
function publish(type){var cropEl=document.getElementById('mpCrop');var qtyEl=document.getElementById('mpQuantity');var unitEl=document.getElementById('mpUnit');var priceEl=document.getElementById('mpPrice');var marketEl=document.getElementById('mpMarket');var descEl=document.getElementById('mpDescription');var deliveryEl=document.getElementById('mpDeliveryDate');var photoEl=document.getElementById('mpPhoto');if(!cropEl||!qtyEl||!priceEl||!qtyEl.value||!priceEl.value){alert('Veuillez remplir les champs obligatoires (produit, quantite, prix).');return;}
var unit=unitEl?unitEl.value:'tonnes';var qtyKg=parseFloat(qtyEl.value)*(UNIT_KG[unit]||1);var body={listing_type:type==='sell'?'offre':'demande',category:_formCategory,culture:cropEl.value,quantity_kg:qtyKg,unit_price_fcfa:parseFloat(priceEl.value),country_iso3:_userIso3()||'BEN',region:marketEl?marketEl.value:null,market_name:marketEl?marketEl.value:null,description:descEl?descEl.value.trim():'',delivery_date:(type==='buy'&&deliveryEl&&deliveryEl.value)?deliveryEl.value:null,photos:[]};var btn=document.getElementById('mpPublishBtn');if(btn){btn.disabled=true;btn.textContent='Publication…';}
var file=(photoEl&&photoEl.files&&photoEl.files[0])?photoEl.files[0]:null;var step=file?_uploadPhoto(file):Promise.resolve(null);step.then(function(url){if(url)body.photos=[url];return fetch(_apiBase()+'/api/marketplace/listings',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}).then(function(r){if(r.status===401||r.status===403){alert('Connectez-vous pour publier une annonce.');return null;}
if(!r.ok)return r.text().then(function(t){throw new Error(t);});return r.json();}).then(function(d){if(!d){if(btn){btn.disabled=false;btn.innerHTML='<i data-lucide="megaphone" class="lc"></i> Publier';if(window.lucide)try{window.lucide.createIcons();}catch(e){}}return;}
alert('Annonce publiee !'+(file&&!body.photos.length?'\n(Photo non envoyee : stockage non configure.)':''));currentTab='marche';render();window.scrollTo(0,0);}).catch(function(e){if(btn){btn.disabled=false;btn.innerHTML='<i data-lucide="megaphone" class="lc"></i> Publier';if(window.lucide)try{window.lucide.createIcons();}catch(ex){}}
alert('Publication impossible : '+(e&&e.message?String(e.message).slice(0,120):'erreur'));});}
function setTab(tabId){currentTab=tabId;render();window.scrollTo(0,0);}
function init(){currentTab='marche';if(typeof syncFromBackend==='function'){syncFromBackend(render);}else{render();}}
function getQRUrl(data,size){size=size||200;try{if(typeof qrcode==='function'){var qr=qrcode(0,'M');qr.addData(String(data));qr.make();var n=qr.getModuleCount();var cell=Math.max(2,Math.round(size/(n+8)));return qr.createDataURL(cell,4);}}catch(e){}
return'';}
function buildTraceData(item){var data={id:item.id,platform:'AgroPrix',type:item.type==='sell'?'VENTE':'ACHAT',product:item.cropName||item.crop,quantity:item.quantity+' '+(item.unit||'kg'),price:item.type==='sell'?(item.price+' FCFA/kg'):(item.maxPrice+' '+item.priceUnit),seller:item.seller||item.buyer||'—',market:item.market||'—',date:item.date?item.date.split('T')[0]:'—',country:getUserCountry(),verified:item.verified?'OUI':'NON',url:'https://agroprix.app/trace/'+item.id};return JSON.stringify(data);}
function getTraceCode(itemId){try{return(JSON.parse(localStorage.getItem('agroprix_trace_codes')||'{}'))[itemId]||null;}
catch(e){return null;}}
function setTraceCode(itemId,code){try{var m=JSON.parse(localStorage.getItem('agroprix_trace_codes')||'{}');m[itemId]=code;localStorage.setItem('agroprix_trace_codes',JSON.stringify(m));}catch(e){}}
function createTraceForItem(item){var d=item.date?String(item.date).split('T')[0]:null;var actor=item.seller||item.buyer||'';var payload={product:item.cropName||item.crop||'Lot agricole',quantity:item.quantity||null,unit:item.unit||'kg',producer_name:actor||null,origin_locality:item.market||null,harvest_date:d,steps:[{label:'Mise en marché',actor:actor,date:d||'',location:item.market||''}]};return fetch((AP.API_BASE||'')+'/api/trace',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(8000)}).then(function(r){if(r.status===401||r.status===403)return{_unauth:true};return r.ok?r.json():null;}).catch(function(){return null;});}
function paintTraceQR(code){var img=document.getElementById('traceQrImg');var msg=document.getElementById('traceQrMsg');var cap=document.getElementById('traceQrCaption');var viewUrl=(AP.API_BASE||'')+'/api/trace/'+code+'/view';if(img){img.src=getQRUrl(viewUrl,250);img.style.display='inline-block';}
if(msg)msg.style.display='none';if(cap)cap.innerHTML='Scannez pour ouvrir la page de tracabilite publique<br>Code : <b>'+code+'</b>';}
function ensureRealTraceQR(item){var cached=getTraceCode(item.id);if(cached){paintTraceQR(cached);return;}
createTraceForItem(item).then(function(res){var msg=document.getElementById('traceQrMsg');var cap=document.getElementById('traceQrCaption');if(res&&res._unauth){if(msg)msg.innerHTML='Connecte-toi pour generer<br>le certificat verifiable';if(cap)cap.textContent='';return;}
if(res&&res.code){setTraceCode(item.id,res.code);paintTraceQR(res.code);return;}
if(msg)msg.textContent='Certificat indisponible (hors ligne).';if(cap)cap.textContent='';});}
function showQR(itemId){var offers=getOffers();var demands=getDemands();var item=offers.find(function(o){return o.id===itemId;})||demands.find(function(d){return d.id===itemId;});if(!item)return;var isSell=item.type==='sell';var container=document.getElementById('marketplaceContent');var html='<button class="action-btn" data-action="mkt-init" style="font-size:12px;margin-bottom:16px;">← Retour au marche</button>';html+='<div class="card" style="padding:20px;text-align:center;margin-bottom:16px;">'
+'<div style="font-size:11px;font-weight:700;color:var(--primary);text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;">Certificat de Tracabilite AgroPrix</div>'
+'<div style="border:3px solid var(--primary);border-radius:16px;padding:16px;display:inline-block;margin-bottom:12px;min-width:180px;">'
+'<img id="traceQrImg" src="" alt="QR Tracabilite" style="width:100%;max-width:200px;height:auto;border-radius:8px;display:none;">'
+'<div id="traceQrMsg" style="font-size:12px;color:#999;padding:24px 8px;">Generation du certificat verifiable...</div>'
+'</div>'
+'<div id="traceQrCaption" style="font-size:11px;color:#999;margin-bottom:12px;">Enregistrement du lot trace...</div>'
+'</div>';html+='<div class="card" style="padding:16px;margin-bottom:16px;">'
+'<div class="card-title"><span class="icon"><i data-lucide="clipboard-list" class="lc"></i></span> Fiche de tracabilite</div>'
+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;">';var fields=[{label:'ID Lot',value:esc(item.id)},{label:'Type',value:isSell?'<i data-lucide="package" class="lc"></i> Vente':'<i data-lucide="shopping-cart" class="lc"></i> Achat'},{label:'Produit',value:esc(item.cropName||item.crop)},{label:'Quantite',value:esc(item.quantity+' '+(item.unit||'kg'))},{label:'Prix',value:isSell?formatFCFA(item.price)+'/kg':esc(item.maxPrice+' '+item.priceUnit)},{label:'Lieu',value:esc(item.market||'—')},{label:isSell?'Vendeur':'Acheteur',value:esc(isSell?item.seller:item.buyer)},{label:'Date',value:esc(item.date?item.date.split('T')[0]:'—')},{label:'Pays',value:esc(getUserCountry())},{label:'Verifie',value:item.verified?'<i data-lucide="check-circle" class="lc"></i> Oui':'<i data-lucide="hourglass" class="lc"></i> En attente'}];fields.forEach(function(f){html+='<div style="background:var(--bg);padding:8px 10px;border-radius:8px;">'
+'<div style="font-size:10px;color:#999;">'+f.label+'</div>'
+'<div style="font-size:13px;font-weight:600;">'+f.value+'</div>'
+'</div>';});html+='</div></div>';html+='<div class="card" style="padding:14px;margin-bottom:16px;background:linear-gradient(135deg,#D8F3DC,#B7E4C7);border:1px solid #2D6A4F33;">'
+'<div style="font-size:12px;font-weight:700;color:#1B4332;margin-bottom:6px;"><i data-lucide="globe-2" class="lc"></i> Conformite reglementation UE</div>'
+'<div style="font-size:11px;color:#2D6A4F;">Ce QR code repond aux exigences du reglement europeen anti-deforestation '
+'(EUDR, applicable juin 2026) qui impose la tracabilite des produits agricoles importes dans l\'UE, '
+'notamment le cacao, le cafe, le soja et le cajou.</div>'
+'</div>';if(isSell){var totalAmount=(item.price||0)*(item.quantity||0)*(item.unit==='tonnes'?1000:1);var isPaid=localStorage.getItem('agroprix_paid_'+item.id);if(isPaid){html+='<div class="card" style="padding:16px;margin-bottom:16px;background:linear-gradient(135deg,#d1fae5,#a7f3d0);border:2px solid var(--green);text-align:center;">'
+'<div style="font-size:32px;margin-bottom:6px;"><i data-lucide="check-circle" class="lc"></i></div>'
+'<div style="font-size:14px;font-weight:700;color:#1B4332;">Paiement confirme</div>'
+'<div style="font-size:12px;color:#047857;margin-top:4px;">'+formatFCFA(totalAmount)+' via Mobile Money</div>'
+'<div style="font-size:10px;color:#059669;margin-top:4px;">Ref: FDP-'+item.id.toUpperCase().substr(0,8)+' | '+new Date().toLocaleDateString('fr')+'</div>'
+'</div>';}else{html+='<div class="card" style="padding:16px;margin-bottom:16px;">'
+'<div class="card-title"><span class="icon"><i data-lucide="credit-card" class="lc"></i></span> Paiement securise</div>'
+'<div style="font-size:12px;color:var(--text-light);margin-bottom:12px;">Payez directement le producteur via Mobile Money. Transaction securisee par FedaPay.</div>'
+'<div style="background:var(--bg);padding:12px;border-radius:10px;margin-bottom:12px;">'
+'<div style="display:flex;justify-content:space-between;font-size:13px;"><span>Produit</span><strong>'+(item.cropName||item.crop)+'</strong></div>'
+'<div style="display:flex;justify-content:space-between;font-size:13px;margin-top:4px;"><span>Quantite</span><strong>'+item.quantity+' '+(item.unit||'kg')+'</strong></div>'
+'<div style="display:flex;justify-content:space-between;font-size:13px;margin-top:4px;"><span>Prix unitaire</span><strong>'+formatFCFA(item.price)+'/kg</strong></div>'
+'<div style="display:flex;justify-content:space-between;font-size:14px;font-weight:800;margin-top:8px;padding-top:8px;border-top:2px solid var(--border);"><span>TOTAL</span><span style="color:var(--green);">'+formatFCFA(totalAmount)+'</span></div>'
+'</div>'
+'<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:12px;">'
+'<div style="text-align:center;padding:10px;border:2px solid var(--border);border-radius:10px;cursor:pointer;" data-action="highlight-border">'
+'<div style="font-size:20px;"><i data-lucide="smartphone" class="lc"></i></div><div style="font-size:10px;font-weight:600;">MTN MoMo</div></div>'
+'<div style="text-align:center;padding:10px;border:2px solid var(--border);border-radius:10px;cursor:pointer;" data-action="highlight-border">'
+'<div style="font-size:20px;"><i data-lucide="smartphone" class="lc"></i></div><div style="font-size:10px;font-weight:600;">Moov Money</div></div>'
+'<div style="text-align:center;padding:10px;border:2px solid var(--border);border-radius:10px;cursor:pointer;" data-action="highlight-border">'
+'<div style="font-size:20px;"><i data-lucide="credit-card" class="lc"></i></div><div style="font-size:10px;font-weight:600;">Carte</div></div>'
+'</div>'
+'<button data-action="mkt-process-payment" data-id="'+item.id+'" style="width:100%;padding:14px;background:linear-gradient(135deg,#E8862A,#E8862A);color:#fff;border:none;border-radius:10px;font-size:14px;font-weight:700;cursor:pointer;">'
+'<i data-lucide="credit-card" class="lc"></i> Payer '+formatFCFA(totalAmount)+'</button>'
+'<div style="display:flex;align-items:center;justify-content:center;gap:6px;margin-top:8px;">'
+'<span style="font-size:9px;color:#999;"><i data-lucide="lock" class="lc"></i> Paiement securise par</span>'
+'<span style="font-size:11px;font-weight:700;color:#1B4332;">FedaPay</span>'
+'</div></div>';}}
html+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:16px;">'
+'<button style="padding:12px;background:var(--primary);color:#fff;border:none;border-radius:10px;font-size:13px;font-weight:600;cursor:pointer;" '
+'data-action="mkt-share-qr" data-id="'+item.id+'"><i data-lucide="share-2" class="lc"></i> Partager</button>'
+'<button style="padding:12px;background:linear-gradient(180deg,#fff,#FAFCFB);color:var(--primary);border:2px solid var(--primary);border-radius:10px;font-size:13px;font-weight:600;cursor:pointer;" '
+'data-action="mkt-init"><i data-lucide="store" class="lc"></i> Retour</button>'
+'</div>';container.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'});ensureRealTraceQR(item);}
function processPayment(itemId){if(typeof window!=='undefined'&&window.alert){window.alert('Paiement marketplace bientot disponible.\n\n'
+'Le paiement entre acteurs (acheteur/vendeur) passera par FedaPay dans '
+'une prochaine mise a jour. Pour l\'instant, prenez contact directement '
+'via WhatsApp ou telephone indique sur l\'offre.');}}
function shareQR(itemId){var offers=getOffers();var demands=getDemands();var item=offers.find(function(o){return o.id===itemId;})||demands.find(function(d){return d.id===itemId;});if(!item)return;var text='Tracabilite AgroPrix\n'
+'Produit: '+(item.cropName||item.crop)+'\n'
+'Quantite: '+item.quantity+' '+(item.unit||'kg')+'\n'
+'Lieu: '+(item.market||'—')+'\n'
+'Date: '+(item.date?item.date.split('T')[0]:'—')+'\n'
+'ID: '+item.id+'\n'
+'Verification: https://agroprix.app/trace/'+item.id;if(navigator.share){navigator.share({title:'Tracabilite AgroPrix',text:text}).catch(function(){});}else{navigator.clipboard.writeText(text).then(function(){alert('Informations de tracabilite copiees !');}).catch(function(){prompt('Copiez les informations de tracabilite :',text);});}}
AP.marketplace={init:init,setTab:setTab,publish:publish,showQR:showQR,shareQR:shareQR,processPayment:processPayment};AP.actions=AP.actions||{};AP.actions['mkt-set-tab']=function(el){AP.marketplace.setTab(el.getAttribute('data-tab'));};AP.actions['mkt-show-qr']=function(el){AP.marketplace.showQR(el.getAttribute('data-id'));};AP.actions['mkt-publish']=function(el){AP.marketplace.publish(el.getAttribute('data-type'));};AP.actions['mkt-init']=function(){AP.marketplace.init();};AP.actions['mkt-process-payment']=function(el){AP.marketplace.processPayment(el.getAttribute('data-id'));};AP.actions['mkt-share-qr']=function(el){AP.marketplace.shareQR(el.getAttribute('data-id'));};AP.actions['mkt-cat-fam']=function(el){_catFilters.category=el.getAttribute('data-value')||'';render();};AP.actions['mkt-cat-type']=function(el){_catFilters.type=el.getAttribute('data-value')||'';render();};AP.actions['mkt-cat-country']=function(){_catCountry=_catCountry?'':_userIso3();render();};AP.actions['mkt-cat-search']=function(){var i=document.getElementById('mktSearch');_catFilters.q=i?i.value:'';render();};AP.actions['mkt-contact']=function(el){contactListing(el.getAttribute('data-id'));};AP.actions['mkt-form-fam']=function(el){_formCategory=el.getAttribute('data-value')||'cultures';render();};AP.actions['mkt-notif-box']=function(el){_notifBox=el.getAttribute('data-value')||'all';render();};AP.actions['mkt-notif-accept']=function(el){respondContact(el.getAttribute('data-id'),'accept');};AP.actions['mkt-notif-refuse']=function(el){respondContact(el.getAttribute('data-id'),'refuse');};})(window.AgroPrix);