/*! AgroPrix ui.js - generated from ui.js.src on 2026-04-18 - DO NOT EDIT; edit the .src file and run `python build_js.py` */
(function(AP){var KOLA_EMAIL='kolawoleogounchi@outlook.com';var PLAN_LEVELS={'free':0,'demo':0,'gratuit':0,'Starter':1,'starter':1,'Pro':2,'pro':2,'Expert':3,'expert':3,'admin':99,'unlimited':99};var VIEW_MIN_PLAN={'analyse':0,'dashboard':0,'params':0,'offres':0,'historique':1,'carte':1,'negoce':1,'opportunites':1,'production':1,'conseilsProducteur':1,'inputs':1,'market':1,'financing':2,'gpsFinancement':2,'scoring':2,'ndvi':2,'hevea':2,'plantain':2,'export':3,'conformite':3};var PLAN_LABELS={0:'Gratuit',1:'Starter — 990 FCFA/mois',2:'Pro — 2 900 FCFA/mois',3:'Expert — 14 900 FCFA/mois'};var PLAN_UPGRADE_TARGET={1:function(){souscrirePlan('Starter',990);},2:function(){souscrirePlan('Pro',2900);},3:function(){souscrirePlan('Expert',14900);}};function getUserPlanLevel(){var user=AP.auth?AP.auth.getUser():null;if(!user)return 0;if(user.email&&user.email.toLowerCase()===KOLA_EMAIL.toLowerCase())return 99;if(user.role==='admin')return 99;var planKey=user.plan||user.role||'free';return PLAN_LEVELS[planKey]!==undefined?PLAN_LEVELS[planKey]:0;}
function showUpgradeModal(requiredLevel){var planLabel=PLAN_LABELS[requiredLevel]||'Plan supérieur';var modal=document.getElementById('upgradeModal');if(!modal){modal=document.createElement('div');modal.id='upgradeModal';modal.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.6);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px;';document.body.appendChild(modal);}
modal.innerHTML='<div style="background:#fff;border-radius:20px;padding:28px;max-width:360px;width:100%;text-align:center;box-shadow:0 20px 60px rgba(0,0,0,0.3);">'
+'<div style="font-size:48px;margin-bottom:8px;"><i data-lucide="lock" style="width:48px;height:48px;color:#E8862A;display:inline-block;"></i></div>'
+'<h3 style="margin:0 0 8px;color:#1B4332;font-size:20px;">Module Réservé</h3>'
+'<p style="font-size:14px;color:#666;margin:0 0 20px;">Ce module nécessite le <strong style="color:#2D6A4F;">'+planLabel+'</strong>.</p>'
+'<button onclick="showView(\'offres\');document.getElementById(\'upgradeModal\').style.display=\'none\';" style="width:100%;padding:14px;background:linear-gradient(135deg,#1B4332,#2D6A4F);color:#fff;border:none;border-radius:12px;font-size:15px;font-weight:700;cursor:pointer;margin-bottom:10px;">'
+'<i data-lucide="trending-up" style="width:16px;height:16px;vertical-align:middle;margin-right:6px;"></i> Voir nos offres</button>'
+'<button onclick="document.getElementById(\'upgradeModal\').style.display=\'none\';" style="width:100%;padding:12px;background:#f5f5f5;color:#666;border:none;border-radius:12px;font-size:14px;cursor:pointer;">Annuler</button>'
+'</div>';modal.style.display='flex';if(window.lucide){try{var mNodes=Array.prototype.slice.call(modal.querySelectorAll('[data-lucide]'));if(mNodes.length)window.lucide.createIcons({nodes:mNodes});}catch(e){}}}
function showView(viewId,el){var minLevel=VIEW_MIN_PLAN[viewId];if(minLevel===undefined)minLevel=0;var userLevel=getUserPlanLevel();if(userLevel<minLevel){showUpgradeModal(minLevel);return;}
document.querySelectorAll('.view-container').forEach(function(v){v.classList.remove('show');v.style.display='none';});var targetId=AP.viewIdMap[viewId]||'viewAnalyse';var target=document.getElementById(targetId);if(target){target.classList.add('show');target.style.display='block';}
document.querySelectorAll('.sidebar-nav a, .bottom-nav a').forEach(function(a){a.classList.remove('active');});if(el)el.classList.add('active');var titleEl=document.getElementById('viewTitle');if(titleEl)titleEl.textContent=AP.viewTitles[viewId]||'AgroPrix';if(viewId==='negoce'||viewId==='opportunites'){if(AP.negoce&&AP.negoce.init)AP.negoce.init();}
if(viewId==='export'){if(AP.exportModule&&AP.exportModule.init)AP.exportModule.init();}
if(viewId==='inputs'){if(AP.inputs&&AP.inputs.init)AP.inputs.init();}
if(viewId==='market'){if(AP.marketplace&&AP.marketplace.init)AP.marketplace.init();}
if(viewId==='financing'){if(AP.financing&&AP.financing.init)AP.financing.init();}
if(viewId==='scoring'){if(AP.scoring&&AP.scoring.render)AP.scoring.render();}
if(viewId==='ndvi'){if(AP.ndvi&&AP.ndvi.init)AP.ndvi.init();}
if(viewId==='production'){window.scrollTo({top:0,behavior:'smooth'});}
closeMobileMenu();setTimeout(refreshIcons,100);}
function toggleSwitch(el){el.classList.toggle('active');}
function toggleCustomDates(){var sel=document.getElementById('periodSelect');var custom=document.getElementById('dateCustom');if(sel&&custom){custom.style.display=sel.value==='custom'?'flex':'none';}}
function updateMarkets(){var countrySelect=document.getElementById('countrySelect');var marketList=document.getElementById('marketsGrid');if(!countrySelect||!marketList)return;var country=countrySelect.value;var markets=AP.marketsByCountry[country]||[];marketList.innerHTML=markets.map(function(mk,idx){return'<label class="market-check"><input type="checkbox" value="'+idx+'" checked><span>'+mk.name+'</span></label>';}).join('');}
function toggleAllMarkets(state){var marketList=document.getElementById('marketsGrid');if(!marketList)return;marketList.querySelectorAll('input[type="checkbox"]').forEach(function(cb){cb.checked=state;});}
function toggleMobileMenu(){var sidebar=document.getElementById('sidebarEl');var overlay=document.getElementById('sidebarOverlay');if(sidebar)sidebar.classList.toggle('open');if(overlay)overlay.classList.toggle('active');}
function closeMobileMenu(){var sidebar=document.getElementById('sidebarEl');var overlay=document.getElementById('sidebarOverlay');if(sidebar)sidebar.classList.remove('open');if(overlay)overlay.classList.remove('active');}
function icon(name,size){size=size||18;return'<i data-lucide="'+name+'" style="width:'+size+'px;height:'+size+'px;display:inline-block;vertical-align:middle;margin-right:4px;"></i>';}
function refreshIcons(scopeEl){if(!window.lucide)return;try{var nodes=[];if(scopeEl){nodes=Array.prototype.slice.call(scopeEl.querySelectorAll('[data-lucide]'));}else{var persistent=document.querySelectorAll('.sidebar [data-lucide], .bottom-nav [data-lucide], #moreMenu [data-lucide]');Array.prototype.forEach.call(persistent,function(n){nodes.push(n);});var visibleView=document.querySelector('.view-container.show');if(visibleView){Array.prototype.forEach.call(visibleView.querySelectorAll('[data-lucide]'),function(n){nodes.push(n);});}
var modals=document.querySelectorAll('#upgradeModal [data-lucide], #errorBoundary [data-lucide], #offlineBanner [data-lucide]');Array.prototype.forEach.call(modals,function(n){nodes.push(n);});}
if(nodes.length>0){window.lucide.createIcons({nodes:nodes});}}catch(e){try{window.lucide.createIcons();}catch(e2){}}}
AP.icon=icon;AP.refreshIcons=refreshIcons;window.icon=icon;window.refreshIcons=refreshIcons;AP.ui={showView:showView,toggleSwitch:toggleSwitch,toggleCustomDates:toggleCustomDates,updateMarkets:updateMarkets,toggleAllMarkets:toggleAllMarkets,toggleMobileMenu:toggleMobileMenu,closeMobileMenu:closeMobileMenu};window.showView=showView;window.toggleSwitch=toggleSwitch;window.toggleCustomDates=toggleCustomDates;window.updateMarkets=updateMarkets;window.toggleAllMarkets=toggleAllMarkets;window.toggleMobileMenu=toggleMobileMenu;window.closeMobileMenu=closeMobileMenu;})(window.AgroPrix);